### ISSUE TITLE
Couldn't bind to persistent volumes

### ISSUE THREAD

**Issue by cenyuzhang** [IBM/wordpress-sample#5]
After following all the instructions, I got the following error:

SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "wp-lv-claim", which is unexpected.

Typing "kubectl get pv" shows the two persistent volumes created - "local-volume-1" & "local-volume-2"

**Comment by Tomcli** [comment]
It looks like at least one of your persistent volumes is bounded to a deployment that is not from our example. Try to run `kubectl get pv` and make sure the persistent volumes are bounded to "mysql-lv-claim" and "wp-lv-claim".

If you don't want to delete your existing deployments and you ran out of persistent volumes to use, you can simply create another persistent volume with a different name and redeploy your Wordpress's PersistentVolumeClaim. 

For example, you can modify and add the following code to your **local-volumes.yaml** file (Note each persistent volume should have a different *name* and *hostPath*). Then you should have enough persistent volumes for your Wordpress and MySQL after you run `kubectl create -f local-volumes.yaml`.

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-x
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/lv-x
  persistentVolumeReclaimPolicy: Recycle
```
